#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-sequence-library
Version  : 1.0.2
Release  : 1
URL      : https://repo1.maven.org/maven2/de/regnis/q/sequence/sequence-library/1.0.2/sequence-library-1.0.2.jar
Source0  : https://repo1.maven.org/maven2/de/regnis/q/sequence/sequence-library/1.0.2/sequence-library-1.0.2.jar
Source1  : https://repo1.maven.org/maven2/de/regnis/q/sequence/sequence-library/1.0.2/sequence-library-1.0.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-sequence-library-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-sequence-library package.
Group: Data

%description data
data components for the mvn-sequence-library package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/de/regnis/q/sequence/sequence-library/1.0.2
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/de/regnis/q/sequence/sequence-library/1.0.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/de/regnis/q/sequence/sequence-library/1.0.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/de/regnis/q/sequence/sequence-library/1.0.2


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/de/regnis/q/sequence/sequence-library/1.0.2/sequence-library-1.0.2.jar
/usr/share/java/.m2/repository/de/regnis/q/sequence/sequence-library/1.0.2/sequence-library-1.0.2.pom
